version: '3.4'

services:
  identity-server:
    image: doitsu2014/identity-service
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Initial:AdminUser:EmailAddress=${SECRET_SERVICES_IDENTITY_INITIAL_ADMIN_USER_EMAIL_ADDRESS}
      - Initial:AdminUser:Password=${SECRET_SERVICES_IDENTITY_INITIAL_ADMIN_USER_PASSWORD}
      - Initial:Application:BlazorClient:ClientId=${SECRET_SERVICES_IDENTITY_INITIAL_BLAZOR_CLIENT_CLIENTID}
      - Initial:Application:BlazorClient:Uri=${SECRET_SERVICES_IDENTITY_INITIAL_BLAZOR_CLIENT_URI}
      - Initial:Application:ServiceGateway:ClientId=${SECRET_SERVICES_IDENTITY_INITIAL_SERVICE_GATEWAY_CLIENTID}
      - Initial:Application:ServiceGateway:ClientSecret=${SECRET_SERVICES_IDENTITY_INITIAL_SERVICE_GATEWAY_CLIENTSECRET}
      - ConnectionStrings:IdentityDatabase=${SECRET_SERVICES_IDENTITY_CONNECTIONSTRING}
      - Certificate:Password=${SECRET_SERVICES_IDENTITY_CERTIFICATE_PASSWORD}
      - Authentication:Google:ClientId=${SECRET_SERVICES_IDENTITY_AUTHENTICATION_GOOGLE_CLIENTID}
      - Authentication:Google:ClientSecret=${SECRET_SERVICES_IDENTITY_AUTHENTICATION_GOOGLE_CLIENTSECRET}
    ports:
      - "5000:80"
    volumes:
      - ./Volumes/appsettings.json:/app/appsettings.json
      - ./Volumes/logs:/app/logs
