version: '3.4'

services:
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=k3ISepyCZzoT06Oi
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./project-volume/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./project-volume/ASP.NET/Https/:/root/.aspnet/https:ro
      - ./project-volume/appsettings.json:/app/appsettings.json
