// <auto-generated />
using System;
using FileConversion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FileConversion.Data.Migrations
{
    [DbContext(typeof(FileConversionContext))]
    partial class FileMappingPipelineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FileConversion.Abstraction.Model.InputMapping", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<int>("InputType");

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("Mapper")
                        .HasMaxLength(256);

                    b.Property<int?>("MapperSourceTextId");

                    b.Property<int>("StreamType");

                    b.Property<string>("XmlConfiguration")
                        .HasMaxLength(4000);

                    b.HasKey("Key", "InputType");

                    b.HasIndex("MapperSourceTextId");

                    b.ToTable("InputMapping");
                });

            modelBuilder.Entity("FileConversion.Abstraction.Model.MapperSourceText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SourceText")
                        .HasMaxLength(4000);

                    b.HasKey("Id");

                    b.ToTable("MapperSourceText");
                });

            modelBuilder.Entity("FileConversion.Abstraction.Model.OutputMapping", b =>
                {
                    b.Property<int>("Key");

                    b.Property<int>("NumberOfFooter");

                    b.Property<int>("NumberOfHeader");

                    b.Property<string>("XmlConfiguration")
                        .HasMaxLength(4000);

                    b.HasKey("Key");

                    b.ToTable("OutputMapping");
                });

            modelBuilder.Entity("FileConversion.Abstraction.Model.InputMapping", b =>
                {
                    b.HasOne("FileConversion.Abstraction.Model.MapperSourceText", "MapperSourceText")
                        .WithMany("InputMappings")
                        .HasForeignKey("MapperSourceTextId");
                });
#pragma warning restore 612, 618
        }
    }
}
