version: '3.4'

services:
  fileconversion-client-blazor:
    image: doitsu2014/fileconversion-client-blazor:latest
    build:
      context: ../../
      dockerfile: Web/Blazor.FileConversion/Blazor.FileConversion.Server/Dockerfile