version: '3.4'

services:
  identity-server:
    image: doitsu2014/identity-service
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./project-volume/appsettings.json:/app/appsettings.json
      - ./project-volume/logs:/app/logs
