version: '3.4'

services:
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zaQ@1234
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./Volumes/secrets:/root/.microsoft/usersecrets:ro
      - ./Volumes/https:/root/.aspnet/https:ro
      - ./Volumes/appsettings.json:/app/appsettings.json
      - ./Volumes/logs:/app/logs

