version: '3.4'

services:
  identity-server:
    image: doitsu2014/identity-service:latest
    build:
      context: ../../
      dockerfile: Services/Identity.Service/Identity.Service.OpenIdServer/Dockerfile

