version: '3.8'

services:
  doitsu.tech.services.identity:
    image: docker-hub.doitsu.tech/services.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./Volumes/appsettings.json:/app/appsettings.json
      - ./Volumes/logs:/app/logs

